name: 'Next.js visual-regression → PDF'
author: 'Cdaprod'
description: >
  Visual regression PDF generator that crawls a Docker-built Next.js app.

inputs:
  context:
    description: 'Docker build context for the app'
    default: '.'
  dockerfile:
    description: 'Dockerfile within the context'
    default: 'Dockerfile'
  port:
    description: 'Port exposed by the container and crawler'
    default: '3000'
  depth:
    description: 'Crawler link depth (0 = only /)'
    default: '2'
  output_dir:
    description: 'Folder (inside repo) to store PDFs'
    default: 'docs/visual-regression'
  keep:
    description: 'How many historical PDFs to keep'
    default: '5'
  commit:
    description: 'Commit/push generated PDFs back to the repo'
    default: 'true'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.context }}
    - ${{ inputs.dockerfile }}
    - ${{ inputs.port }}
    - ${{ inputs.depth }}
    - ${{ inputs.output_dir }}
    - ${{ inputs.keep }}
    - ${{ inputs.commit }}
